CREATE DATABASE QLTRUONGHOC
USE QLTRUONGHOC


CREATE TABLE THANHTRA(
	MATHANHTRA varchar(30) PRIMARY KEY,
	TENTHANHTRA nvarchar(30),
	SDT varchar(10),
)

CREATE TABLE MONHOC(
	MAMONHOC varchar(30) PRIMARY KEY,
	TENMONHOC nvarchar(50),
	LOAIMONHOC nvarchar(50),
	TONGTIETMONHOC int,
)

CREATE TABLE BANGCAP(
	MABANGCAP varchar(30) PRIMARY KEY,
	TENBANGCAP nvarchar(30),
	DONGIATIETVUOT float,
)

CREATE TABLE NAMHOC(
	MANAMHOC varchar(30) PRIMARY KEY,
	NAMBATDAU int,
	NAMKETTHUC int,
)

CREATE TABLE HOCHAM(
	MAHOCHAM varchar(30) PRIMARY KEY,
	TENHOCHAM nvarchar(30),
)

CREATE TABLE HOCVI(
	MAHOCVI varchar(30) PRIMARY KEY,
	TENHOCVI nvarchar(30),
)

CREATE TABLE CHUCVU(
	MACHUCVU varchar(30) PRIMARY KEY,
	TENCHUCVU nvarchar(30),
	HESOCHUCVU float,
)

CREATE TABLE HESOTHIDUA(
	MAHESOTHIDUA varchar(30) PRIMARY KEY,
	MUCNHAN float,
)

CREATE TABLE HANGGIANGVIEN(
	MAHANGGV varchar(30) PRIMARY KEY,
	TENHANG nvarchar(30),
)

CREATE TABLE HESOLUONG(
	HESOLUONG float PRIMARY KEY,
	HANGGV varchar(30),
	FOREIGN KEY (HANGGV) REFERENCES  HANGGIANGVIEN(MAHANGGV),
)

CREATE TABLE GIANGVIEN(
	MAGIANGVIEN varchar(30) PRIMARY KEY,
	TENGIANGVIEN nvarchar(30),
	NGAYSINH DATE,
	GIOITINH nvarchar(5),
	QUEQUAN nvarchar(30),
	THAMNIENCONGTAC int,

	HOCHAM varchar(30),
	FOREIGN KEY (HOCHAM) REFERENCES  HOCHAM(MAHOCHAM),
	
	HOCVI varchar(30),
	FOREIGN KEY (HOCVI) REFERENCES  HOCVI(MAHOCVI),

	CHUCVU varchar(30),
	FOREIGN KEY (CHUCVU) REFERENCES  CHUCVU(MACHUCVU),

	HESOTHIDUA varchar(30),
	FOREIGN KEY (HESOTHIDUA) REFERENCES  HESOTHIDUA(MAHESOTHIDUA),

	HESOLUONG float,
	FOREIGN KEY (HESOLUONG) REFERENCES  HESOLUONG(HESOLUONG),
)


CREATE TABLE GV_BC(
	MABANGCAP varchar(30),
	MAGIANGVIEN varchar(30),
	PRIMARY KEY (MABANGCAP,MAGIANGVIEN),
	FOREIGN KEY (MABANGCAP) REFERENCES  BANGCAP(MABANGCAP),
	FOREIGN KEY (MAGIANGVIEN) REFERENCES  GIANGVIEN(MAGIANGVIEN),
)

CREATE TABLE LICHDAY(
	MALICHDAY varchar(30) PRIMARY KEY,
	MAGIANGVIEN varchar(30),
	MANAMHOC varchar(30),
	MAMONHOC varchar(30),
	NGAYDAY date,
	TIETBATDAU int,
	TIETKETTHUC int,
	TONGTIETDAY int,
	FOREIGN KEY (MAGIANGVIEN) REFERENCES  GIANGVIEN(MAGIANGVIEN),
	FOREIGN KEY (MANAMHOC) REFERENCES  NAMHOC(MANAMHOC),
	FOREIGN KEY (MAMONHOC) REFERENCES  MONHOC(MAMONHOC),
)

CREATE TABLE THUCDAY(
	MATHUCDAY varchar(30) PRIMARY KEY,	
	NGAYTHUCDAY date,
	SOTIETTHUCDAY int,
	GHICHU nvarchar(50),
	MALICHDAY  varchar(30),
	MATHANHTRA varchar(30),
	FOREIGN KEY (MATHANHTRA) REFERENCES  THANHTRA(MATHANHTRA),
	FOREIGN KEY (MALICHDAY) REFERENCES  LICHDAY(MALICHDAY),
)