using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BUS;
using MaterialSkin.Controls;

namespace GUI
{
    public partial class FormThemMoiNguoiDung : MaterialForm
    {
        private QuanLyNguoiDung quanLyNguoiDung;

        public FormThemMoiNguoiDung()
        {
            quanLyNguoiDung = new QuanLyNguoiDung();

            InitializeComponent();
        }

        public void SetUpControls()
        {
           
        }

        private void FormThemMoiNguoiDung_Load(object sender, EventArgs e)
        {
            SetUpControls();
        }

        private void btnTaoNgauNhien_Click(object sender, EventArgs e)
        {
            txtTenDangNhap.Text = quanLyNguoiDung.GetAutoGeneratedUsername();
            txtMatKhau.Text = quanLyNguoiDung.GetAutoGeneratedPassword();
            checkBoxHoatDong.Checked = true;
        }

        private void btnLuu_Click(object sender, EventArgs e)
        {
            if(CheckInput())
            {
                if (quanLyNguoiDung.InsertNguoiDung(txtTenDangNhap.Text, txtMatKhau.Text, checkBoxHoatDong.Checked))
                {
                    MessageBox.Show("Thêm mới người dùng thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    Close();
                }
                else
                {
                    MessageBox.Show("Thêm mới người dùng thất bại", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            else
            {
                return;
            }
        }

        private bool CheckInput()
        {
            if(txtTenDangNhap.Text == "")
            {
                MessageBox.Show("Tên đăng nhập không được để trống", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }

            if (txtMatKhau.Text == "")
            {
                MessageBox.Show("Mật khẩu không được để trống", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }

            return true;
        }
    }
}
